version: '3'
services:
  app:
    tty: true
    build: .
    ports:
      - "${SERVER_APP_PORT-8266}:8266"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    depends_on:
      - mongo
      - redis
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development
      MONGO_DSN: mongodb://mongo:27017/oh-behave
      REDIS_DSN: redis://redis:6379/0
      PORT: ${SERVER_APP_PORT-8266}
      DEBUG: ${DEBUG}
      LEGACY_DSN: ${LEGACY_DSN}
      ANALYTICS_DSN: ${ANALYTICS_DSN}
      PLATFORM_DSN: ${PLATFORM_DSN}
      RADIX_DSN: ${RADIX_DSN}
  redis:
    image: redis:alpine
  mongo:
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - "${SERVER_DB_PORT-8267}:27017"
volumes:
  node_modules: {}
  mongodb: {}
